import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { isPyInt, pyDecodeUtf8, pyEncodeUtf8, pyInt, pyItem } from '../python_builtins.ts';

interface Fixture {
  decode: Array<{ hex: string; text?: string; error?: string; replace: string }>;
  encode: Array<{ value: string; ok?: boolean; error?: string }>;
  int16: Array<{ value: string; int?: string; error?: string }>;
}

const fixture = JSON.parse(
  readFileSync(join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'python_builtins.json'), 'utf8'),
) as Fixture;

describe('CPython builtins used by the ports (fixture generated by CPython 3.12)', () => {
  it("bytes.decode('utf-8') keeps a BOM and reports CPython's error ranges; errors='replace' matches too", () => {
    for (const c of fixture.decode) {
      const bytes = Buffer.from(c.hex, 'hex');
      if (c.error === undefined) expect(pyDecodeUtf8(bytes)).toBe(c.text);
      else expect(() => pyDecodeUtf8(bytes)).toThrow(new Error(c.error));
      expect(pyDecodeUtf8(bytes, 'replace')).toBe(c.replace);
    }
  });

  it("str.encode('utf-8') refuses lone surrogates with CPython's message", () => {
    for (const c of fixture.encode) {
      if (c.ok) expect(Buffer.from(pyEncodeUtf8(c.value)).toString('utf8')).toBe(c.value);
      else expect(() => pyEncodeUtf8(c.value)).toThrow(new Error(c.error));
    }
  });

  it('int(s, 16) accepts and rejects exactly what CPython does', () => {
    for (const c of fixture.int16) {
      if (c.int !== undefined) {
        expect(pyInt(c.value, 16).toString()).toBe(c.int);
        expect(isPyInt(c.value, 16)).toBe(true);
      } else {
        expect(() => pyInt(c.value, 16)).toThrow(new Error(c.error));
        expect(isPyInt(c.value, 16)).toBe(false);
      }
    }
  });

  it('dict[key] raises a KeyError-shaped error', () => {
    expect(pyItem({ a: 1 }, 'a')).toBe(1);
    expect(() => pyItem({}, 'expiration')).toThrow(new Error("'expiration'"));
  });
});
