import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bytesFromHex } from '../bytes_from_hex.ts';
import { ChainError, ChainErrorKinds } from '../errors.ts';
import { pyBytesRepr, pyRepr, pyStr, pyStrRepr, pyTypeRepr } from '../python_repr.ts';

interface Fixture {
  fromhex: Array<{ input: string; hex?: string; error?: string }>;
  str: Array<{ value: string; repr: string }>;
  bytes: Array<{ hex: string; repr: string }>;
  nested: Array<{ value: unknown; repr: string }>;
}

const fixture = JSON.parse(
  readFileSync(join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'python_text_semantics.json'), 'utf8'),
) as Fixture;

describe('bytesFromHex matches CPython bytes.fromhex (fixture generated by CPython 3.12)', () => {
  it.each(fixture.fromhex.map((c) => [JSON.stringify(c.input), c] as const))('%s', (_label, c) => {
    if (c.hex !== undefined) {
      expect(Buffer.from(bytesFromHex(c.input)).toString('hex')).toBe(c.hex);
    } else {
      expect(() => bytesFromHex(c.input)).toThrow(new ChainError(ChainErrorKinds.InvalidArgument, c.error as string));
    }
  });

  it('never echoes the input in its error', () => {
    const secretLike = `${'ab'.repeat(16)}zz${'cd'.repeat(15)}`;
    const error = (() => {
      try {
        bytesFromHex(secretLike);
      } catch (err) {
        return err as Error;
      }
      return null;
    })();
    expect(error?.message).toBe('non-hexadecimal number found in fromhex() arg at position 32');
    expect(error?.message).not.toContain('abab');
  });
});

describe('pyRepr / pyStr / pyTypeRepr match CPython repr() / str() / type()', () => {
  it('str repr', () => {
    for (const c of fixture.str) expect(pyStrRepr(c.value)).toBe(c.repr);
  });

  it('bytes repr', () => {
    for (const c of fixture.bytes) expect(pyBytesRepr(Buffer.from(c.hex, 'hex'))).toBe(c.repr);
  });

  it('None, booleans, ints, lists and dicts', () => {
    for (const c of fixture.nested) expect(pyRepr(c.value)).toBe(c.repr);
  });

  it('str() prints strings bare, errors by message and everything else as repr', () => {
    expect(pyStr('abc')).toBe('abc');
    expect(pyStr(new Error('boom'))).toBe('boom');
    expect(pyStr(null)).toBe('None');
    expect(pyStr(false)).toBe('False');
  });

  it('type() renders like <class ...>', () => {
    expect(pyTypeRepr(null)).toBe("<class 'NoneType'>");
    expect(pyTypeRepr('x')).toBe("<class 'str'>");
    expect(pyTypeRepr(1)).toBe("<class 'int'>");
    expect(pyTypeRepr({})).toBe("<class 'dict'>");
    expect(pyTypeRepr(new Map())).toBe("<class 'Map'>");
  });
});
