import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PyJsonDumpsOptions, pyJsonDumps } from '../python_json.ts';
import { pyFloatRepr } from '../python_repr.ts';
import { AbstractSignedTransaction } from '../signed_transaction.ts';
import { StellarSignedTransaction, StellarUnsignedTransaction } from '../stellar/stellar_transactions.ts';
import { TronSignedTransaction, TronUnsignedTransaction } from '../tron/tron_transactions.ts';
import { UnsignedTransaction } from '../unsigned_transaction.ts';

interface PythonKwargs {
  indent?: number | string;
  sort_keys?: boolean;
  separators?: [string, string];
  ensure_ascii?: boolean;
}

interface Fixture {
  transactions: Array<{ payload: string; kwargs: PythonKwargs; text: string }>;
  dumps: Array<{ value: unknown; kwargs: PythonKwargs; text: string }>;
  floats: Array<{ bits: string; repr: string }>;
}

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(join(here, 'fixtures', 'python_json_dumps.json'), 'utf8')) as Fixture;
const payloads = JSON.parse(readFileSync(join(here, 'fixtures', 'omnichain_py_transaction_payloads.json'), 'utf8')) as Record<string, Record<string, unknown>>;

const decoders: Record<string, (payload: Record<string, unknown>) => UnsignedTransaction | AbstractSignedTransaction> = {
  stellar_unsigned: (p) => StellarUnsignedTransaction.fromJson(p),
  stellar_signed: (p) => StellarSignedTransaction.fromJson(p),
  tron_unsigned: (p) => TronUnsignedTransaction.fromJson(p),
  tron_signed: (p) => TronSignedTransaction.fromJson(p),
};

function options(kwargs: PythonKwargs): PyJsonDumpsOptions {
  return { indent: kwargs.indent, sortKeys: kwargs.sort_keys, separators: kwargs.separators, ensureAscii: kwargs.ensure_ascii };
}

describe('toJsonStr is byte-identical to omnichain-py to_json_str (text generated by Python)', () => {
  it.each(fixture.transactions.map((c) => [`${c.payload} ${JSON.stringify(c.kwargs)}`, c] as const))('%s', (_label, c) => {
    const tx = decoders[c.payload](payloads[c.payload]);
    expect(tx.toJsonStr(options(c.kwargs))).toBe(c.text);
  });
});

describe('pyJsonDumps matches CPython json.dumps', () => {
  it('random nested values with unicode, control characters and floats', () => {
    for (const c of fixture.dumps) expect(pyJsonDumps(c.value, options(c.kwargs))).toBe(c.text);
  });

  it('NaN / Infinity follow allow_nan', () => {
    expect(pyJsonDumps([Number.NaN, Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY])).toBe('[NaN, Infinity, -Infinity]');
    expect(() => pyJsonDumps(Number.NaN, { allowNan: false })).toThrow('Out of range float values are not JSON compliant: nan');
  });
});

describe('pyFloatRepr matches CPython repr(float)', () => {
  it('600 doubles, including subnormals, integral floats and the fixed/scientific boundaries', () => {
    for (const c of fixture.floats) expect(pyFloatRepr(Buffer.from(c.bits, 'hex').readDoubleBE(0))).toBe(c.repr);
  });
});
